### PR TITLE
Read multiple files

### PR DESCRIPTION
**Pull request by stebru**
Trying to handle #14. Don't know if I'm on the right track here... The problem is that 6to5 only outputs the first source path to the `sources` array in the .map file.

Edit: ... and looks like sourceFileName option is required when using to5.transform

### CODE REVIEW

**Comment by sindresorhus** [comment]
This a job for grunt-contrib-concat.

**Comment by stebru** [comment]
neat-o

**Comment by abelnation** [comment]
How would you go about handling the sourcemap issue?  Babel generates sourcemaps for individual files, which when concatenated, would invalidate the original sourcemap.  Thoughts?

**Comment by mikemclin** [comment]
Babel CLI gives you the ability to compile directories to one concatenated file.  Can't this be supported?

https://babeljs.io/docs/usage/cli/

**Pull request closed without merging**
